# Generated by Django 5.0.7 on 2024-08-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
