# Generated by Django 5.0.7 on 2024-08-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_event_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='ACI, RM 202', max_length=80),
            preserve_default=False,
        ),
    ]
