# Generated by Django 5.0.7 on 2024-08-27 06:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_event_registration_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
